# Source: https://github.com/Wandmalfarbe/pandoc-latex-template
# Chinese tutorial: <https://ask.latexstudio.net/ask/article/768.html>

{{- if eq .chezmoi.os "windows" }}

["AppData/Roaming/pandoc/templates"]
    type = "archive"
    url = "https://github.com/Wandmalfarbe/pandoc-latex-template/releases/latest/download/Eisvogel.zip"
    refreshPeriod = "672h"
    include = ["eisvogel.latex", "icon.png", "examples/**"]

{{- else if eq .chezmoi.os "darwin" }}

[".local/share/pandoc/templates"]
    type = "archive"
    url = "https://github.com/Wandmalfarbe/pandoc-latex-template/releases/latest/download/Eisvogel.zip"
    refreshPeriod = "672h"
    include = ["eisvogel.latex", "icon.png", "examples/**"]

{{- else if eq .chezmoi.os "linux" }}

[".local/share/pandoc/templates"]
    type = "archive"
    url = "https://github.com/Wandmalfarbe/pandoc-latex-template/releases/latest/download/Eisvogel.zip"
    refreshPeriod = "672h"
    include = ["eisvogel.latex", "icon.png", "examples/**"]

{{- end }}
