[data]
    email = "inkfinite@qq.com"
    name = "inkfin"
    profile = ""

[git]
    autoCommit = false
    autoPush = false

[diff]
    command = "nvim"
    args = [ "-d", "{{ .Destination }}", "{{ .Target }}" ]

[merge]
    command = "nvim"
    args = [ "-d", "{{ .Destination }}", "{{ .Source }}" ]
