#!/usr/bin/env sh
# Open a new Ghostty tab running nushell

exec osascript -e 'tell application "Ghostty"
set cfg to new surface configuration
set command of cfg to "nu"
new tab in front window with configuration cfg
end tell'
