import = [
    "~/.config/alacritty/profiles/common.toml",
    "~/.config/alacritty/fonts/fantasque_nf.toml",
    "~/.config/alacritty/keybindings/keybindings.toml",
]

working_directory = "%APPDATA%/../../../"

[window]
decorations = "None"
padding = { x = 3, y = 3 }
opacity = 0.7
startup_mode = "Fullscreen"
dynamic_title = false
title = "popup"
