# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
    { on = "l", run = "plugin smart-enter", desc = "smart enter" },
    { on = "<Enter>", run = "plugin smart-enter", desc = "smart enter" },
    { on = "S", run = 'shell "$SHELL" --block --confirm' },
    { on = "<C-g>", run = "shell --confirm --block lazygit", desc = "Lazygit" },
]
