# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = [ "l" ]
run = "plugin smart-enter"
desc = "smart enter"

[[manager.prepend_keymap]]
on = [ "<Enter>" ]
run = "plugin smart-enter"
desc = "smart enter"

[[manager.prepend_keymap]]
on = [ "S" ]
run = 'shell "$SHELL" --block --confirm'
desc = "enter shell (cwd)"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = [ "<C-g>" ]
run = 'shell --confirm --block lazygit'
desc = "Lazygit"

[[manager.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

# [[manager.prepend_keymap]]
# on = "<C-y>"
# run = ["plugin system-clipboard"]
# desc = "Copy to system clipboard"
