[data]
    email = "inkfinite@qq.com"
    name = "inkfin"
    profile = "personal"
[git]
    autoCommit = false
    autoPush = false
[diff]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Target }}"]
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}"]
